
# Post a device.
POST http://localhost:5000/api/devices
Content-Type: application/json

"serialNumber": "123334455667"

###

# Assign a Device
PUT http://localhost:5000/api/devices/assign
Content-Type: application/json

{
    "patientId": "71976b71-faf3-468c-a304-8c75b541dcc3",
    "deviceId": ""
}
###

# Post a patient
POST http://localhost:5000/api/patients
Content-Type: application/json

{
  "firstName": "sergey",
  "lastName": "bulavskiy",
  "dateOfBirth": "03.08.1993"
}

