
# Post a device.
Get http://localhost:5000/api/devices?serialNumber=123334455667
Content-Type: application/json

###

# Assign a Device
PUT http://localhost:5000/api/devices/assign
Content-Type: application/json

{
    "patientId": "71976b71-faf3-468c-a304-8c75b541dcc3",
    "deviceId": "71976b71-faf3-468c-a304-8c75b541dcc3"
}
###

# Post a patient
POST http://localhost:5000/api/patients
Content-Type: application/json

{
  "firstName": "david",
  "lastName": "gilmour",
  "dateOfBirth": "06.03.1946",
  "email": "david.gilmour@gmail.com"
}

